### PR TITLE
fix(setup-tutorial.ts) json error

### PR DESCRIPTION
**Pull request by tudorpintea999**
Hello,
In the saveWalletFile function, the data string is not correctly formatted as JSON.
The closing quote for the privateKey value is missing
I changed the code
Hope it helps
Br,
Tudor.

### CODE REVIEW

**Review by andresaiello — APPROVED** [review]

**Comment by andresaiello** [comment]
good catch! thank you!

**Comment by andresaiello** [comment]
please rebase to latest version to merge it

**Comment by tudorpintea999** [comment]
is it ok now?

**Comment by andresaiello** [comment]
will check with the team why I can't merge it

**Pull request merged**
